### ISSUE TITLE
一加5T用1.2版的短信有时会恢复成Oxygen默认的，强行停止再打开又OK了

### ISSUE THREAD

**Issue by Elietio** [ttimasdf/OnePlusExtension#1]

**Comment by ttimasdf** [comment]
Emmmm…你会编译这个项目吗？代码里还有另一个方法修改短信app，但是我把它注释掉了……

**Comment by Elietio** [comment]
JAVA会一些，但是安卓完全没弄过，这个等你方便再弄就行啦，谢了，我先试试用idea能不能打包成功

**Comment by ttimasdf** [comment]
如果方便的话，你运行这个命令pull下来短信App的程序发这里来，我看看和我的有啥不一样（我是OP3）
```sh
adb pull /system/priv-app/OPMms/oat/arm64/OPMms.odex
```

我感觉应该差不多啦=，=

**Comment by Elietio** [comment]
额，我看了一下并没有odex文件，只有apk和lib ⊙﹏⊙‖∣，Android O beta2
![qq 20180122180834](https://user-images.githubusercontent.com/14260539/35215489-5f90f2e4-ff9f-11e7-966e-03e56a938442.png)

**Comment by snipking** [comment]
同样的问题，我发现似乎是每次收到短信以后通过 notification 进入 message 的时候有这个问题

**Comment by ttimasdf** [comment]
通过通知进去的时候应该短信应用已经启动了吧，验证码和服务号的识别在通知里显示正常吗？

**Comment by snipking** [comment]
@ttimasdf 嗯，应该不是通知导致的，有时候是好的有时候不行，没找到规律

**Comment by ttimasdf** [comment]
[app-debug.zip](https://github.com/ttimasdf/OnePlusExtension/files/1676453/app-debug.zip)

试试这个 @Elietio @snipking 。没更新版本号，如果装不了的话可能需要卸载之前版本 😅 
5T的版本，好像加了另一个判断系统的方法，虽然解决掉了但我没找到在哪儿调用的……就很迷

**Comment by Elietio** [comment]
@ttimasdf 嗯，试用了一天，正常了，多谢！

**Comment by snipking** [comment]
@ttimasdf 同正常，多谢！
