### ISSUE TITLE
[request]magisk版

### ISSUE THREAD

**Issue by MaiTestarossa** [ttimasdf/OnePlusExtension#3]
xposed没法过safetynet，我装的有些付费app会检查safetynet
想要氢的来电识别和短信识别
希望能出个magisk版

**Comment by ttimasdf** [comment]
不存在的……
magisk只能覆盖文件，不能热修改代码。一加那么些机型里面带的apk包版本也不是完全一样，比如我的OP3里SMS版本是1.4，前面issues里面提到的OP5是1.2。没办法弄一个统一的安装包，而且即使有这么个包的话以后还要费心随官方更新，就很麻烦了 😓
