### ISSUE TITLE
短信识别可以使用，但没有分类，电话识别之前可以后来不知道为什么不可以用了

### ISSUE THREAD

**Issue by monkey-sking** [ttimasdf/OnePlusExtension#5]
短信识别可以使用，但没有分类，电话识别之前可以后来不知道为什么不可以用了
一加3T，Android8

**Comment by ttimasdf** [comment]
电话识别可能需要更新号码库。试试这个 [auxiliary/YuloreFramework-aligned-signed.apk](https://github.com/ttimasdf/OnePlusExtension/blob/master/auxiliary/YuloreFramework-aligned-signed.apk?raw=true)

**Comment by monkey-sking** [comment]
下载后安装，提示更新，最后没有安装成功
