### ISSUE TITLE
YuloreFramework-aligned-signed.apk 安装不了

### ISSUE THREAD

**Issue by gythialy** [ttimasdf/OnePlusExtension#6]
一加 3T，Android 8.0，显示 App not installed

**Comment by ttimasdf** [comment]
adb install 看看报啥错？

**Comment by oqo0opo** [comment]
adb install YuloreFramework-aligned-signed.apk
2811 KB/s (13685310 bytes in 4.752s)
Failure [INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package com.yulore.framework signatures do not match the previously installed version; ignoring!]

**Comment by ttimasdf** [comment]
说明以前你安装过这个包的原版，或者系统里已经自带了它。我觉得你的情况应该是后者。
你可以用 `adb shell pm path com.yulore.framework` 看看它装在哪儿了。

**Comment by oqo0opo** [comment]
adb shell pm path com.yulore.framework
package:/system/app/YuloreFramework/YuloreFramework.apk

直接在rootexplorer里面替换试试

**Comment by ttimasdf** [comment]
那就不必了。说明你系统里已经有了就不用装了。改system分区反而会破坏系统盘校验，过不了SafetyNet

**Comment by gythialy** [comment]
``` shell 
# adb 安装 liuliangbao.apk 和 YuloreFramework-aligned-signed.apk

λ adb install -r liuliangbao.apk
Success

λ adb install -r YuloreFramework-aligned-signed.apk
adb: failed to install YuloreFramework-aligned-signed.apk: Failure [INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package com.yulore.framework signatures do not match the previously installed version; ignoring!]

# 检查安装
λ adb shell pm path com.oupeng.max.sdk
package:/data/app/com.oupeng.max.sdk-IJRaGKmzigU3jtCqyC00CA==/base.apk

λ adb shell pm path com.yulore.framework
package:/system/app/YuloreFramework/YuloreFramework.apk

# 很奇怪的是 流量包默认竟然是禁用状态的，在 UI 界面也不能启用，手动通过 pm 启用
λ adb shell pm list package -d
package:com.oupeng.max.sdk

λ adb shell pm enable com.oupeng.max.sdk
Package com.oupeng.max.sdk new state: enabled

# 再次确认 
λ adb shell pm list packages -d
```

PS. 如果说系统自带 `com.yulore.framework` 且是启用状态，是不是说就应该能正常使用？
PSS.  话说安装了 xposed 是肯定过不了 SafetyNet 校验的吧？

**Comment by ttimasdf** [comment]
1. 是呀。
2. 是呀。

但人家xposed好歹有个开关不是，改了系统盘万一哪天想用了就得刷机了。
